#!/bin/bash

username='JohnBerd'

dir=$(basename "$PWD")
curl -u 'JohnBerd' https://api.github.com/user/repos -d \{\"name\":\"$dir\"\}
git init
git add --all
git commit -m "first commit"
git remote add origin git@github.com:JohnBerd/$dir
git push -u origin master
